Paginate through StackResources before deploying static
architect/deploy pull request #277
Opened 2020-10-29 22:20 UTC by samirrayani

resolves: https://github.com/architect/deploy/issues/996

## Thank you for helping out! ✨

### We really appreciate your commitment to improving Architect

To maintain a high standard of quality in our releases, before merging every pull request we ask that you've completed the following:

- [x] Forked the repo and created your branch from `master`
- [x] Made sure tests pass (run `npm it` from the repo root)
- [ ] Expanded test coverage related to your changes:
  - [ ] Added and/or updated unit tests (if appropriate)
  - [ ] Added and/or updated integration tests (if appropriate)
- [ ] Updated relevant documentation:
  - [ ] Internal to this repo (e.g. `readme.md`, help docs, inline docs & comments, etc.)
  - [ ] [Architect docs (arc.codes)](https://github.com/architect/arc.codes)
- [x] Summarized your changes in `changelog.md`
- [x] Linked to any related issues, PRs, etc. below that may relate to, consume, or necessitate these changes

Please also be sure to completed the CLA (if you haven't already).

Learn more about [contributing to Architect here](https://arc.codes/intro/community).

Thanks again!

2020-10-29 22:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/architect/deploy?pullRequest=277) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/architect/deploy?pullRequest=277) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/architect/deploy?pullRequest=277) it.</sub>

2020-10-29 22:23 UTC, samirrayani commented
use this as an example reference: https://github.com/architect/deploy/blob/master/src/dirty/deploy-nested-stack.js#L34-L61

2020-11-15 14:05 UTC, filmaj requested changes
Hey @samirrayani, thanks for sending a PR for this! I think we need a few changes, though:

1. One sub-optimal thing is that this implementation will gather all the pages of results from `listStackResources` before searching for the bucket. I think we should tweak the implementation such that, as each page of results is pulled in, we search for the bucket we are looking for, and if we find it, we short-circuit out of the recursive loop and return the `PhysicalResourceId`. This way we only call `listStackResources` as many times as we need to.
2. We should add tests for this behaviour.

I recently opened a PR solving this exact problem in a different repo (see https://github.com/architect/logs/pull/302) (also includes a test) which can be used as a reference, in case that's helpful.

2020-11-16 18:58 UTC, ryanblock commented
Fix will be released in 8.3 – sorry I wasn't able to use this PR, Deploy had a very meaty refactor. Gave you a shout out in release notes though!

2020-11-16 18:58 UTC, closed without merging